### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by happytm** [DieBieEngineering/DieBieMS#1]
What are the specifications for this board? specially compared to http://electrodacus.com/SBMS100/manual/SBMSmanual.pdf

**Comment by lpasselin** [comment]
> Solar BMS can be used with 3 up to 8 Lithium cells (any type)

Most DIY kits are 10S with 18650.

SBMS is less convenient as an electric skateboard BMS.

**Comment by DieBieEngineering** [comment]
It is indeed oriented towards smal electric vehicles with their corresponding size and functional requirements.
