### ISSUE TITLE
How turn on this BMS?

### ISSUE THREAD

**Issue by rakhmaevao** [DieBieEngineering/DieBieMS#13]
Hi. I assembled the device.
HW 0.8
I connected battery. I upload firmware. Device connecting in DieBieMSTool.
I connect pin J14:2 to GND. Terminal DieBieMS says the button is pressed.

> -----Battery Pack Status-----
Pack voltage          : 24.52V
Pack current          : 0.04A
Low  current          : 0.04A
High current          : 0.00A
State of charge       : 0.0%
Remaining capacity    : 0.00Ah
Operational state     : Power down
Load voltage          : 0.00V
Cell voltage high     : 3.506V
Cell voltage low      : 3.503V
Cell voltage average  : 3.505V
Cell voltage mismatch : 0.003V
Discharge enabled     : False
Charge enabled        : False
Power button pressed  : True
---End Battery Pack Status---

But BMS not connected LOAD and battery. OpState remains Power down.

How turn on this BMS?

**Comment by DieBieEngineering** [comment]
Ok ltc seems to work and ISL as well!

However the power button should not indicate pressed unless it is actually
pressed. You don't have a button connected right?

**Comment by rakhmaevao** [comment]
Thanks for the quick feedback.
I really like this BMS.
> Ok ltc seems to work and ISL as well!

Yes, it work.

> However the power button should not indicate pressed unless it is actually
> pressed. You don't have a button connected right?

I not have special button, but i connect pin 2 J14 connector to pin 1 J14 connector.
If i connect pin 2 to pin 1, terminal says "Power button pressed  : True".
If pin 2 is not connected to pin 1,  terminal says "Power button pressed  : False".

Firmware: V0.21
Name    : DieBieMS
UUID: 2D 00 23 00 02 57 34 54 32 37 38 20

**Comment by DieBieEngineering** [comment]
Ok in that case it works as it should. The power button input should be a
momentary switch.

I'll explain a bit more in a sec. Did you also find the skateboard forum?

**Comment by rakhmaevao** [comment]
Oh, Denny. Your forum not accessed in my region (Russia). Proxy in my provider not let through vpn.
I use cash google for reading forum.((
По делу:
If I press button, and device see it, should the device turn on?
I will try to understand. Please, don't leave me in github.
See also issue in [tool repositories](https://github.com/DieBieEngineering/DieBieMS-Tool/issues), and 
[bootloader repositories](https://github.com/DieBieEngineering/DieBieMS-Bootloader/issues).


I connect 4,5, 6, 7, 8 IC7 to 3.3 V (i upgraded code firmware:
`driverHWSwitchesSetSwitchState(SWITCH_DRIVER,(driverHWSwitchesStateTypedef)SWITCH_SET);
driverHWSwitchesSetSwitchState(SWITCH_CHARGE,(driverHWSwitchesStateTypedef)SWITCH_SET);
driverHWSwitchesSetSwitchState(SWITCH_PRECHARGE,(driverHWSwitchesStateTypedef)SWITCH_SET);
driverHWSwitchesSetSwitchState(SWITCH_DISCHARGE,(driverHWSwitchesStateTypedef)SWITCH_SET);`


Voltmeter measures 3,3 V (see fig below)
![image](https://user-images.githubusercontent.com/33318971/54682499-2434fd80-4b20-11e9-974d-ef6c9576fc3d.png)
But Q2 and Q3 not opened. voltage between pin 11 and 12 equals 0 V.

**Comment by rakhmaevao** [comment]
Oh, my BQ76200PW destroyed.
I changed it and everything works.
