### ISSUE TITLE
What fuser are you using?

### ISSUE THREAD

**Issue by rakhmaevao** [DieBieEngineering/DieBieMS#3]
The photo shows a large fuse, but it is not in bom.
What fuser are you using?

**Comment by b264** [comment]
Is it one of these? [Leistungssicherung Streifensicherung Sicherung Midi / weiss / 80A / 58V](https://www.amazon.de/Leistungssicherung-Streifensicherung-Sicherung-Midi-weiss/dp/B00EBNRXRK/ref=mp_s_a_1_4)
