### ISSUE TITLE
Update DieBieMS Readme

### ISSUE THREAD

**Issue by tojon** [DieBieEngineering/DieBieMS#4]
The Readme could be improved with a couple of quick typo fixes and removes some trailing white space. Feel free to use the upcoming PR or just close this Issue and PR and wrap the changes into your own work :)

**Comment by tojon** [comment]
So we've merged this change, and @DieBieEngineering will do additional work in is own subsequent PRs. Marking this Issue as fixed and Closed.

**Comment by tojon** [comment]
Actually I think Danny might need to do this for best practice, since he's the Repo Owner and I don't have project permissions.

**Comment by DieBieEngineering** [comment]
The suggested changes are merged, thanks for the assistance!
