### ISSUE TITLE
BMS

### ISSUE THREAD

**Issue by SwiftFlying** [DieBieEngineering/DieBieMS#8]
Hi,
I am TOM from China. I am interested in BMS. Are you interested in our cooperation in developing a commercial BMS?

**Comment by DieBieEngineering** [comment]
Hi! You are free to use all files in any way or kind and resell it ( but please use genuine and real parts, although sometimes expensive....) .

I have multiple projects going, maybe in the future I'll make it more compact and cheaper, nothing on the short term I am afraid.
