### ISSUE TITLE
Where is version 0.8 in GIT?

### ISSUE THREAD

**Issue by rakhmaevao** [DieBieEngineering/DieBieMS#9]
Where is version 0.8 in GIT?
There is 0.7, then 0.9.
![image](https://user-images.githubusercontent.com/33318971/51374527-5e7c2180-1b14-11e9-9163-b13bc85dcf7f.png)

**Comment by DieBieEngineering** [comment]
I am afraid I didn't tag it but it is somewhere in between, I am still learning GitHub and need to work a bit cleaner. Nothing significant changed trough!
